---
kind: pipeline
type: docker
name: build-on-runner3

trigger:
  event: [push, custom]
  branch: [master]
  ref: [refs/heads/master]

node:
  site: windows

steps:
  - name: who-am-i
    image: alpine:3.20
    commands:
      - echo "DRONE_STAGE_MACHINE=${DRONE_STAGE_MACHINE}"
      - cat /proc/sys/kernel/hostname

  # --- NEW: quick GPU health check ---
- name: gpu-check
  image: nvidia/cuda:12.6.2-base-ubuntu22.04
  environment:
    NVIDIA_VISIBLE_DEVICES: all
    NVIDIA_DRIVER_CAPABILITIES: compute,utility
  commands:
    - echo "Listing NVIDIA devices (if mapped):"
    - ls -l /dev/nvidia* || true
    - echo "Running nvidia-smi:"
    - nvidia-smi

