---
kind: pipeline
type: docker
name: build-default

trigger:
  event: [push, custom]
  branch: [master]
  ref: [refs/heads/master]

steps:
  - name: who-am-i
    image: alpine:3.20
    commands:
      - echo "DRONE_STAGE_MACHINE=${DRONE_STAGE_MACHINE}"
      - cat /proc/sys/kernel/hostname

---
kind: pipeline
type: docker
name: build-on-runner2
depends_on: [build-default]

trigger:
  event: [push, custom]
  branch: [master]
  ref: [refs/heads/master]

# 👇 singular 'node', must match ALL labels on the runner
node:
  site: app2

steps:
  - name: who-am-i
    image: alpine:3.20
    commands:
      - echo "DRONE_STAGE_MACHINE=${DRONE_STAGE_MACHINE}"
      - cat /proc/sys/kernel/hostname

---
kind: pipeline
type: exec
name: build-windows
depends_on: [build-default]

platform:
  os: windows
  arch: amd64

trigger:
  event: [push, custom]
  branch: [master]
  ref: [refs/heads/master]

# target the Windows Exec runner with label site:windows
node:
  site: windows

# runs directly on the Windows host (requires .NET SDK installed on that machine)
steps:
  - name: who-am-i
    commands:
      - 'powershell -NoLogo -Command "Write-Output \"DRONE_STAGE_MACHINE=$env:DRONE_STAGE_MACHINE\"; hostname"'
