---
kind: pipeline
type: docker
name: build-default

platform:
    os: linux
    arch: amd64

trigger:
    event: [push, custom]
    branch: [master]
    ref: [refs/heads/master]

steps:
    - name: who-am-i
      image: alpine:3.20
      commands:
          - echo "DRONE_STAGE_MACHINE=${DRONE_STAGE_MACHINE}"
          - cat /proc/sys/kernel/hostname

---
kind: pipeline
type: docker
name: build-on-runner2

# run this pipeline only after the first one succeeds
depends_on:
    - build-default

platform:
    os: linux
    arch: amd64

trigger:
    event: [push, custom]
    branch: [master]
    ref: [refs/heads/master]

# target runner2 by label (make sure the runner has DRONE_RUNNER_LABELS=site:app2)
nodes:
    site: app2

steps:
    - name: who-am-i
      image: alpine:3.20
      commands:
          - echo "DRONE_STAGE_MACHINE=${DRONE_STAGE_MACHINE}"
          - cat /proc/sys/kernel/hostname
