name: Publish doorbelld (Linux x64 AOT)

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  publish-linux-x64-aot:
    runs-on: ubuntu-24.04  # has clang/LLVM preinstalled

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cache ccache (speed up clang/lld relinks for NativeAOT)
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/*.csproj', '**/Directory.Packages.props', 'DoorbellSvc.sln') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Setup .NET 9 (with NuGet cache)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: |
            DoorbellSvc.sln
            **/*.csproj
            **/Directory.Packages.props
            nuget.config

      - name: Restore (solution)
        run: dotnet restore DoorbellSvc.sln

      - name: Publish NativeAOT (linux-x64, single-file, self-contained)
        env:
          # Route clang via ccache; lld is the default linker on this image.
          CC: "ccache clang"
          CXX: "ccache clang++"
        run: |
          dotnet publish ./DoorbellSvc/DoorbellSvc.csproj \
            -c Release \
            -r linux-x64 \
            --self-contained true \
            -p:PublishAot=true \
            -p:PublishSingleFile=true \
            -p:StripSymbols=true \
            -p:DebugType=None \
            -p:InvariantGlobalization=true \
            -p:AssemblyName=doorbelld

      - name: Show output
        run: |
          PUBLISH_DIR="./DoorbellSvc/bin/Release/net9.0/linux-x64/publish"
          ls -lah "$PUBLISH_DIR"
          file "$PUBLISH_DIR/doorbelld" || true
          echo "PUBLISH_DIR=$PUBLISH_DIR" >> "$GITHUB_ENV"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: doorbelld-linux-x64
          path: ${{ env.PUBLISH_DIR }}/doorbelld
          if-no-files-found: error

      - name: Upload full publish folder
        uses: actions/upload-artifact@v4
        with:
          name: doorbelld-publish-linux-x64
          path: ${{ env.PUBLISH_DIR }}/
          if-no-files-found: error
